name: Build

on: 
  workflow_dispatch:
  push:
    branches: 
      - 'master'
    paths-ignore:
      - 'readme.md'
    tags:
      - '**'
  pull_request:
    types: [opened, synchronize, reopened]

concurrency: alphavantage_api

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: 'csharp'

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: |
          6.0.x
          7.0.x

    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build -c Release --no-restore
    - name: Test
      env:
        ALPHAVANTAGEOPTIONS__APIKEY: ${{ secrets.AlphaVantageApiKey }}
        ALPHAVANTAGEOPTIONS__MAXAPICALLSPERMINUTE: 35
      run: dotnet test -c Release --no-build --verbosity normal

    - name: Upload coverage reports to Codecov with GitHub Action
      uses: codecov/codecov-action@v3
      
    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2

    - name: Package 
      if: startsWith(github.ref, 'refs/tags/')
      run: dotnet pack -c Release --no-build -o nupkgs
    - name: Push to Nuget
      if: startsWith(github.ref, 'refs/tags/')
      run: dotnet nuget push "./nupkgs/*.nupkg" --source "https://api.nuget.org/v3/index.json" --api-key ${{ secrets.NUGETPUBLISHKEY }}
    - name: Create Release
      if: startsWith(github.ref, 'refs/tags/')
      uses: ncipollo/release-action@v1
      with:
        generateReleaseNotes: 'true'
        makeLatest: 'true'
